spring.application.name=JpaLab02-boot

# 데이터 베이스 연결 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1588/FREEPDB1
spring.datasource.username=choi
spring.datasource.password=java

# 커넥션 풀링 설정
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5 
spring.datasource.hikari.connection-timeout=60000

# Hibernate + JPA 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
# 로깅 설정
logging.level.root=error
logging.level.com.zaxxer.hikari=info
logging.level.kr.or.ddit=info
#파라미터 바인딩
logging.level.org.hibernate.orm.jdbc.bind=trace

#인터페이스가 없어도 클래스 대상으로 프록시 적용
spring.aop.proxy-target-class=true

server.port=80

springdoc.swagger-ui.path=/swagger-ui.html
