spring.application.name=JpaLab02-boot-1

# 데이터 베이스 연결 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1588/FREEPDB1
spring.datasource.username=choi
spring.datasource.password=java

