spring.aop.proxy-target-class=true

server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

# Hibernate + JPA 설정
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
# 로깅 설정
logging.level.root=error
logging.level.com.zaxxer.hikari=info
logging.level.com.example=info
#파라미터 바인딩
logging.level.org.hibernate.orm.jdbc.bind=trace
