# Database connection settings
hibernate.connection.url=jdbc:oracle:thin:@localhost:1588/FREEPDB1
hibernate.connection.username=choi
hibernate.connection.password=java

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
hibernate.hbm2ddl.auto=validate